/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VisitedRouteImport } from './routes/visited'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TempleSlugRouteImport } from './routes/temple.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitedRoute = VisitedRouteImport.update({
  id: '/visited',
  path: '/visited',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleSlugRoute = TempleSlugRouteImport.update({
  id: '/temple/$slug',
  path: '/temple/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/visited': typeof VisitedRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/temple/$slug': typeof TempleSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/visited': typeof VisitedRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/temple/$slug': typeof TempleSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/visited': typeof VisitedRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/temple/$slug': typeof TempleSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/planner'
    | '/profile'
    | '/visited'
    | '/wishlist'
    | '/api/chat'
    | '/temple/$slug'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/planner'
    | '/profile'
    | '/visited'
    | '/wishlist'
    | '/api/chat'
    | '/temple/$slug'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/explore'
    | '/planner'
    | '/profile'
    | '/visited'
    | '/wishlist'
    | '/api/chat'
    | '/temple/$slug'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  ExploreRoute: typeof ExploreRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  VisitedRoute: typeof VisitedRoute
  WishlistRoute: typeof WishlistRoute
  ApiChatRoute: typeof ApiChatRoute
  TempleSlugRoute: typeof TempleSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visited': {
      id: '/visited'
      path: '/visited'
      fullPath: '/visited'
      preLoaderRoute: typeof VisitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple/$slug': {
      id: '/temple/$slug'
      path: '/temple/$slug'
      fullPath: '/temple/$slug'
      preLoaderRoute: typeof TempleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  ExploreRoute: ExploreRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  VisitedRoute: VisitedRoute,
  WishlistRoute: WishlistRoute,
  ApiChatRoute: ApiChatRoute,
  TempleSlugRoute: TempleSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
