INSERT INTO public.temples (slug, name, category, deity, state, city, latitude, longitude, description, best_time, hero_image, tags, is_hidden_gem)
VALUES
  ('chettinad-heritage', 'Chettinad Heritage Village', 'historical', NULL, 'Tamil Nadu', 'Karaikudi', 10.1744271, 78.7813025, 'Grand 19th-century Chettiar mansions, Athangudi tile floors and legendary Chettinad cuisine — one of Tamil Nadu''s most underrated cultural circuits.', 'Nov – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZPbwErAnd9XrnzDD3SyTg0pvfR0OXuu01p5Rl5ua_GpoeoLyk_LwuH0Snyw3twOtOOKmyySvGpqkWEazFSAltqnYW6_Iooqxq9er0dQTtti8brqiOwdeAYfHeaXw3XDZ0TzY1RMDQ2vNWYo8A=s4800-w430', ARRAY['heritage','architecture','food']::text[], TRUE),
  ('tranquebar', 'Tharangambadi (Tranquebar)', 'beach', NULL, 'Tamil Nadu', 'Tharangambadi', 11.0246638, 79.8556599, 'A sleepy Danish colonial seaside town with Fort Dansborg, cobbled streets and a hauntingly beautiful shoreline.', 'Nov – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZOJjEG5l8LMeWcBkmi3k7g2tqvjrPUUKGjVBqWNKoOtelnCIThWQO_VK9dSKTYvDMPG7UuwsD6hXzmKwLhZgH9i4EYiwAstUnMohflTSa6gWGLGvqI50iNPHHzXKoUoVPh7FpMUtKajbc3LD-0=s4800-w1600', ARRAY['beach','colonial','danish-fort']::text[], TRUE),
  ('poompuhar', 'Poompuhar', 'beach', NULL, 'Tamil Nadu', 'Poompuhar', 11.1434459, 79.8577925, 'Ancient Chola port town of Kaveripoompattinam — Sangam-era ruins, museums and a calm beach at the mouth of the Kaveri.', 'Nov – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZP25JFSi-ZQZDKdSdU30jk1VhU9FkXUvlMEfpborUUprSrR_fre_zzQJbLYhSac330bN04znwOm-LFz7mbfeuwbW435gjySkrCSXSSBtwHlfOGQCbTdbOuuavdMSUQD45iYlmiHdKnCxpZRtw=s4800-w1600', ARRAY['ancient-port','sangam','beach']::text[], TRUE),
  ('kolli-hills', 'Kolli Hills', 'hill', NULL, 'Tamil Nadu', 'Namakkal', 11.324535, 78.336786, 'The ''Mountain of Death'' — 70 hairpin bends lead to jackfruit forests, Agaya Gangai waterfall and the mystical Arapaleeswarar shrine.', 'Mar – May, Oct – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZNQ59xl52_BA3yxeiMVPl0SCW8VPxIMgg2MkiMsqDhgR9rZ6RUhf7_srLnzds3pD4JR7on2KG2mgaxBETjuj7l94QZf2AmFWjOp3ff5IWNEC1smpZMcInHWkRJIQ9lwXfAXR74mW5kTa51juqNtDvecAQ=s4800-w1600', ARRAY['hills','waterfall','70-hairpins']::text[], TRUE),
  ('kotagiri', 'Kotagiri', 'hill', NULL, 'Tamil Nadu', 'Kotagiri', 11.40843, 76.8735222, 'The oldest and quietest of the three Nilgiri hill stations — Catherine Falls, tea estates and Kodanad viewpoint without Ooty''s crowds.', 'Mar – May, Sep – Nov', 'https://lh3.googleusercontent.com/place-photos/AJRVUZN-dNWx14xfQAmHHOJlZ2HyIn4HzXwcm4DlSpc6m0GOhuIe4_Tv-TQGDaxmxEoWIg4Iszam4Vxxwxxis-beVRIqg85dQ5Q5EJGbUDVKHXV-AvbD9uXHv2SuqZG76uw-xx0s2GAqz7XbsTl6KQ=s4800-w1600', ARRAY['nilgiris','tea','quiet']::text[], TRUE),
  ('valparai', 'Valparai', 'hill', NULL, 'Tamil Nadu', 'Valparai', 10.3727437, 76.9314426, '40 hairpin bends into the Anamalai tiger reserve — rolling tea, lion-tailed macaques and Aliyar reservoir.', 'Mar – Sep', 'https://lh3.googleusercontent.com/place-photos/AJRVUZNKm060jUidUEnMTKTrap48fGAxQjB_sFvNuknIXab0WFNmeegzp69rxGHwOwe4vppyTY-1uapUX26yd9Ux0t5NcE1ems4eOT1Nh6zt4yrvQhQxXx0aq4ANSKMKKWjFUn7412xGwpp_FLN5=s4800-w1600', ARRAY['anamalai','wildlife','tea']::text[], TRUE),
  ('vagamon', 'Vagamon', 'hill', NULL, 'Kerala', 'Vagamon', 9.6672407, 76.9210404, 'Rolling green meadows, pine forests and India''s paragliding capital — Kerala''s answer to Scotland.', 'Sep – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZNBZb6H1ThamDJEQrmHTZovzwaxVw_4pgTOi6O3h8sr4ThFPeSUVjUCWk8CxJh7U7poFYBt258vGtuvZWiTPwCic_SzxmW8tJmw2y2mZ3YplZ3MExbsoJsDQ-c4riEcTB-A6iPdojafiCywkOxJHIytMA=s4800-w1076', ARRAY['meadows','paragliding','pine-forest']::text[], TRUE),
  ('athirappilly', 'Athirappilly Falls', 'waterfall', NULL, 'Kerala', 'Athirappilly', 10.2851072, 76.5697643, 'The ''Niagara of India'' — 80 ft of thundering Chalakudy river best seen in monsoon.', 'Jun – Nov', 'https://lh3.googleusercontent.com/place-photos/AJRVUZNlWmRuWruclrVaKgZDNzUhMeEvFDzXLiml0xdQLZ4cR16-KpLY3cm0l6pRAgV3g7BphPuhi18QepEWeFicYI_83pPQ9HxcU_A3eFK8ehl_4cZIP6UEe_K6eEEqLbYK0rULl8B2jpCU21FcIA=s4800-w1024', ARRAY['monsoon','niagara','forest']::text[], TRUE),
  ('meghamalai', 'Meghamalai (High Wavy Mountains)', 'hill', NULL, 'Tamil Nadu', 'Theni', 9.7364621, 77.422583, 'The ''High Wavy Mountains'' — cardamom plantations wrapped in perpetual cloud, barely on any tourist map.', 'Jun – Sep, Oct – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZMk3Z2r0As-GnQVY9arPu05MOk8mzjgFxiZ6b6nFhmKOqzNSJIXQogFRw57l2S4MYer6lmq4y2gRhi0kXncU9nZKaZgVUr5t1SZLKsHSCLfEA5WKg76wh-U6UzlAE70Azar-GU0R9MMjiexkA=s4800-w1600', ARRAY['cloud-forest','cardamom','wildlife']::text[], TRUE),
  ('pichavaram', 'Pichavaram Mangroves', 'beach', NULL, 'Tamil Nadu', 'Chidambaram', 11.431882, 79.7810468, 'World''s second-largest mangrove forest — quiet backwater rowboat rides through a green labyrinth.', 'Nov – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZPbZPpiNpiASym4QbPiQsAfCXVBQ0CcVdhMrVrkbzdps1hHAGQCYi0dtgfuVUNdydIQu7joFdAWnzA9-9m-qA0qjGf8y-hz-nJ1luiWxd015trqzggKB2SJaYyUvmnVK9HfhrF-5UwSv7Ht=s4800-w600', ARRAY['mangrove','backwater','boating']::text[], TRUE),
  ('gangaikonda-cholapuram', 'Gangaikonda Cholapuram', 'shiva', 'Shiva (Brihadeeswarar)', 'Tamil Nadu', 'Jayankondam', 11.2063794, 79.4494846, 'The forgotten Chola capital — a UNESCO temple as grand as Thanjavur, but with almost no crowd.', 'Nov – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZOcxzGCKYccavYNtS7l4tFZYaPidtgro2dmLYZ6KXrGsUDF3yJ4P0ccpe4iDK-rzrFIUJ1FaGDNiyCHvepqXRPc0vDoJpu0mnUW81la_Ne6glTcaQg9E5dypj9cd0zLiq_0tKRSRfodIviqY5BTXq1I=s4800-w1600', ARRAY['unesco','chola','architecture']::text[], TRUE),
  ('sittanavasal', 'Sittanavasal Cave', 'historical', NULL, 'Tamil Nadu', 'Pudukkottai', 10.4557516, 78.7250782, '2nd-century Jain rock-cut cave with fresco paintings older than Ajanta — an art-history secret.', 'Nov – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZM3VJ4-bla9bBJPhJGhW5p7zLc2sqEHEdwCJYFolBBF5w5PXWNI3WmmHlDxep0plynIOXM71qQcBgwpPvKydzxGIbkmty8DweFffJpFt3VpFn8N5xP_g2kTL6NjG3t0nOs1ReqmjJxQqtzejA=s4800-w1600', ARRAY['jain','cave','fresco']::text[], TRUE),
  ('marudhamalai', 'Marudhamalai Murugan Temple', 'murugan', 'Murugan', 'Tamil Nadu', 'Coimbatore', 11.046568, 76.8517068, '1,200-year-old hilltop Murugan temple on the Western Ghats above Coimbatore — panoramic sunrise views.', 'Oct – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZM-o1I1mbDIJajV_7-AmrX7Pfac3SDpQH0qL2LEICxReYhjbALZXrhs1EmCB_lXIslAbhzuyF3Snya3aPGujX8qgj-gf7k_4TlINrJFlgyhpER9j7SPmRXRT1xW2ZKnTCGNnAcCjyTQBbB2KG8=s4800-w1600', ARRAY['western-ghats','murugan','view']::text[], FALSE),
  ('sadhuragiri', 'Sadhuragiri Malai', 'shiva', 'Shiva / Siddhars', 'Tamil Nadu', 'Watrap', 9.7272883, 77.6186383, 'A mystical siddhar mountain above the Western Ghats — 8 km trek to a Shiva shrine wrapped in monsoon mist.', 'Jun – Sep', 'https://lh3.googleusercontent.com/place-photos/AJRVUZOgKhpJ-WjMlkXxaWY1St7KDRQg2JCCu2Sw3X7NxWgBclKxtqQbQzys1C5JTvU_ugy6ZZv_ZZw1BmoxApov_IzUB47Qs0Rhlq0HJ0hWfTXiMbXOobU69jrJL0ANviK_8vMiQeQSE0dWC2WcTQ=s4800-w1600', ARRAY['trek','siddhar','monsoon']::text[], TRUE),
  ('agumbe', 'Agumbe', 'hill', NULL, 'Karnataka', 'Agumbe', 13.4965165, 75.0805657, 'The ''Cherrapunji of the South'' — king cobra country, Malgudi Days village and India''s finest west-coast sunset.', 'Jun – Sep', 'https://lh3.googleusercontent.com/place-photos/AJRVUZNwKi5fZJ-5m6iDCfjwO45GiRozefqGv7QHcqUyypcLNEZtKcF2TO4izSlj9RZca1g6tYAfHyPeJ4WD0_OcyVX_x3huMwgL4UhFILMNZ0X4UmL1KHZ5ZkXGnlAg5cueXHy7t2Q25gXq8iWnWQ=s4800-w1600', ARRAY['rainforest','king-cobra','sunset']::text[], TRUE),
  ('thiruparankundram', 'Thiruparankundram Murugan', 'murugan', 'Murugan', 'Tamil Nadu', 'Madurai', 9.8801051, 78.0713555, 'First of Murugan''s six sacred abodes (Arupadai Veedu) — a rock-cut cave temple where the god married Deivayanai.', 'Nov – Feb', 'https://lh3.googleusercontent.com/place-photos/AJRVUZPbEliLpUtjdZT53ttQmC7DJQl53swojMl5pzDt4ECRRCXZiXoTekD3uHdM4IizcMOaA4Q1e66dbBRPmxig0lOdDnDn37rl7ktuU-CA4Se3gu7GwsMBImz5mHzB9lQEZVSkANMYESQaOV43x5iml8N4Mw=s4800-w1600', ARRAY['arupadai','rock-cut','murugan']::text[], FALSE)
ON CONFLICT (slug) DO UPDATE SET
  hero_image = EXCLUDED.hero_image,
  best_time  = EXCLUDED.best_time,
  description = EXCLUDED.description,
  latitude   = EXCLUDED.latitude,
  longitude  = EXCLUDED.longitude,
  tags       = EXCLUDED.tags,
  is_hidden_gem = EXCLUDED.is_hidden_gem;